services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: efva
      POSTGRES_PASSWORD: efva-pw
      POSTGRES_DB: efva-db
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U efva -d efva-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    image: efva-app-dev