services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: efva
      POSTGRES_PASSWORD: efva-pw
      POSTGRES_DB: efva-db
    volumes:
      - efva_db_vol:/var/lib/postgresql/data
      - ./efva.sql:/docker-entrypoint-initdb.d/efva.sql
    ports:
      - 5433:5432

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: efva-app-dev
    ports:
      - 3000:3000


volumes:
  efva_db_vol: