services:
  db:
    volumes:
      - efva_db_vol:/var/lib/postgresql/data
      - ./efva.sql:/docker-entrypoint-initdb.d/efva.sql
    environment:
      POSTGRES_PASSWORD: 'efva-pw'

  app:
    build:
      target: dev
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    stop_signal: SIGINT
    entrypoint: ["uwsgi", "dev-uwsgi.ini"]


volumes:
  efva_db_vol:
