services:
  db:
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
    environment:
      POSTGRES_PASSWORD: 'efva-pw'

  app:
    build:
      target: testing
    volumes:
      - ./:/app/
    image: efva-app-test
    entrypoint: ["pytest", "-o", "pythonpath=.", "-o", "testpaths=tests"]
